### ISSUE TITLE
Lab 1 Issue with python server command

### ISSUE THREAD

**Issue by EvelynGriffith** [Allegheny-Computer-Science-302-F2020/cs302-F2020-plans#4]
I need help with the Python command that was used in the Lab#1 for CMPSC 302. (link to the assignment sheet below)
https://github.com/Allegheny-Computer-Science-302-F2020/computer-science-302-fall-2020-lab-1-EvelynGriffith

The problem is that whenever I put this command, "python -m http.server --directory src/html/learning-objectives" into my terminal window, it comes out with this "Serving HTTP on :: port 8000 (http://[::]:8000/) ..."
Whenever I click to follow the link to the website, it says that the website can't be reached. 
 - I have been making sure to use the command in the terminal window only after I have cded to the right folder.
 - I have also tried using the link provided by professor Kapfhammer: http://0.0.0.0:8000/ , instead of following the link that I got from the python command, but that yielded the same result. 

Below is the text from the assignment sheet that I am currently stuck on. I just copied and pasted it.

"Running a Web Server
Your GitHub repository contains an file called web-development.html in the src/html/learning-objectives. Another way to see how the Markdown file from the previous step should correctly render is to run a web server that points to the directory containing this HTML file and then to load that server into your web browser. Upon completing this step you should be able to see the correct headers and lists that should be in the web-development.md file. Ultimately, the rendered content of your web-web-development.md should match the rendered content in the course planning repository and in your web browser as it views the HTML from your server. Here is the command to type in your terminal window for starting the HTTP server using the Python programming language on your laptop:

python -m http.server --directory src/html/learning-objectives
When I look in my terminal window after accessing the file served by this HTTP server I see the following output. Can you explain what this output means? What output do you see in your terminal window?

127.0.0.1 - - [08/Sep/2020 13:26:54] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Sep/2020 13:26:56] "GET /web-development.html HTTP/1.1" 200 -"

When I was completing the assignment, I thought that the python command would lead me to the website, but for whatever reason, my computer isnt compatible with the output link that was produced from the python command listed above.

My laptop is a Windows 10 Computer. I have windows 10 pro as my software. On my laptop I have docker, VS Code, Git Bash, and Python downloaded for CMPSC 302. In VS Code the current extensions that I am using are 
PS C:\Users\gforc\OneDrive\Documents\labs\cs302F2020\computer-science-302-fall-2020-lab-1-EvelynGriffith>

I need to have this issue resolved as soon as is possible, but it must be before tuesday, so the latest that I can work on it would be monday night.

**Comment by EvelynGriffith** [comment]
Hello, I wanted to add an update to my bug report. Professor Kapfhammer asked me to see which Python version I have in my computer. I have version 3.8.2.

**Comment by gkapfham** [comment]
Hi @EvelynGriffith thanks for posting all of these details about the defect that you are facing. My impression is that you were able to resolve this issue by ensuring that you ran the correct command and that you loaded the page in your web browser by using the web site address as http://localhost:8000. Is that correct?

Some key points that I remember from our discussion include:

- The diagnostic output from the server does not give an address that you can click on in Windows 10 Pro
- It is important to use the http and not the https protocol for this web server
- It is important to avoid typing something like ".com" after the URL

Can you please confirm that you got everything working? Are there any other points that you want to share before we close this issue?

**Comment by gkapfham** [comment]
Hi@EvelynGriffith can you please confirm that this issue wear correctly resolved and then close the issue if it is? Thanks!

**Comment by EvelynGriffith** [comment]
This issue was solved! Thank you!
